name: movie_app_repository
description: The Movie App repository providing repository  access to the Movie App API
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  cache:
    path: ../cache
  
  equatable: ^2.0.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.0
  json_annotation: ^4.9.0
 
  movie_app_api:
    path: '../../data/movie_app_api'

dev_dependencies:
  build_runner: ^2.0.0
  firebase_auth_platform_interface: ^7.0.5
  firebase_core_platform_interface: ^5.0.0
  json_serializable: ^6.3.1
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.7
  very_good_analysis: ^6.0.0
